[package]
name = "avros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
avro-rs = "0.13.0"
similar = "2.2.0"
assert-json-diff = "2.0.2"